cd "d:/k210-c/kendryte_3-standalone/build"
SET ACTEL_FOR_ALTIUM_OVERRIDE= 
SET ALLUSERSPROFILE=C:\ProgramData
SET ALTERA_FOR_ALTIUM_OVERRIDE= 
SET APPDATA=C:\Users\kevin\AppData\Roaming
SET CommonProgramFiles=C:\Program Files\Common Files
SET CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
SET CommonProgramW6432=C:\Program Files\Common Files
SET COMPUTERNAME=DESKTOP-GF0N2DE
SET ComSpec=C:\Windows\system32\cmd.exe
SET DriverData=C:\Windows\System32\Drivers\DriverData
SET HOMEDRIVE=C:
SET HOMEPATH=\Users\kevin
SET KENDRYTE_IDE_LOCAL_PACKAGE_DIR=D:\programfiles\updater.beta.20190604.4.win32\KendryteIDE\LocalPackage
SET KENDRYTE_IDE_UPDATER=D:\programfiles\updater.beta.20190604.4.win32\KendryteIDE\Updater\electron.exe
SET KENDRYTE_IDE_UPDATER_CONTENT_ROOT=D:\programfiles\updater.beta.20190604.4.win32\KendryteIDE
SET KENDRYTE_IDE_UPDATER_IS_BUILT=yes
SET KENDRYTE_IDE_UPDATER_PIPE=\\?\pipe\C:\Users\kevin\AppData\Local\Temp\KendryteIDE_Cache\46758_updater.sock
SET KENDRYTE_IDE_UPDATER_PIPE_ID=1
SET LOCALAPPDATA=C:\Users\kevin\AppData\Local
SET LOGONSERVER=\\DESKTOP-GF0N2DE
SET MGC_HOME=C:\MentorGraphics\9.5PADS\MGC_HOME.ixn
SET NUMBER_OF_PROCESSORS=8
SET OneDrive=C:\Users\kevin\OneDrive
SET OS=Windows_NT
SET PADS_PROGRAMS=Programs
SET PADS_ROOT=C:\MentorGraphics\9.5PADS\SDD_HOME
SET Path=d:\programfiles\updater.beta.20190604.4.win32\KendryteIDE\bin;D:\programfiles\updater.beta.20190604.4.win32\KendryteIDE\LocalPackage\toolchain\bin;D:\programfiles\updater.beta.20190604.4.win32\KendryteIDE\LocalPackage\cmake\bin;D:\programfiles\updater.beta.20190604.4.win32\KendryteIDE\LocalPackage\jlink;D:\programfiles\updater.beta.20190604.4.win32\KendryteIDE\LocalPackage\clang-format\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH
SET PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
SET PROCESSOR_ARCHITECTURE=AMD64
SET PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
SET PROCESSOR_LEVEL=6
SET PROCESSOR_REVISION=8e0a
SET ProgramData=C:\ProgramData
SET ProgramFiles=C:\Program Files
SET ProgramFiles(x86)=C:\Program Files (x86)
SET ProgramW6432=C:\Program Files
SET PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files\Intel\Wired Networking\
SET PUBLIC=C:\Users\Public
SET SDD_CES=ces
SET SDD_COMMON_BIN=C:\MentorGraphics\9.5PADS\SDD_HOME\common\win32\bin
SET SDD_DOC_UTILS=doc_utils
SET SDD_HOME=C:\MentorGraphics\9.5PADS\SDD_HOME
SET SDD_HSSD=hssd
SET SDD_ICDB=iCDB
SET SDD_LOCAL=C:\Documents and Settings\All Users\Application Data\mgc\win32\9.5PADS
SET SDD_MGC_HOME=..\MGC_HOME.ixn
SET SDD_PADS=pads
SET SDD_PLATFORM=win32
SET SDD_START=start
SET SDD_STARTBAT=start /b /wait
SET SDD_TRN=translators
SET SDD_VCD=camcad
SET SDD_VERSION=9.5PADS
SET SDD_WG=wg
SET SDD_WV=wv
SET SESSIONNAME=Console
SET SystemDrive=C:
SET SystemRoot=C:\Windows
SET SYSTEM_TEMP=C:\Users\kevin\AppData\Local\Temp
SET TEMP=C:\Users\kevin\AppData\Local\Temp\KendryteIDE_Cache
SET TMP=C:\Users\kevin\AppData\Local\Temp\KendryteIDE_Cache
SET TMPDIR=C:\Users\kevin\AppData\Local\Temp\KendryteIDE_Cache
SET USERDOMAIN=DESKTOP-GF0N2DE
SET USERDOMAIN_ROAMINGPROFILE=DESKTOP-GF0N2DE
SET USERNAME=kevin
SET USERPROFILE=C:\Users\kevin
SET VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\
SET VSCODE_CWD=D:\programfiles\updater.beta.20190604.4.win32\KendryteIDE\Updater
SET VSCODE_IPC_HOOK=\\.\pipe\88ae827e263a0177b501c53244b5b25b-1.34.1-beta-main-sock
SET VSCODE_LOGS=D:\programfiles\updater.beta.20190604.4.win32\KendryteIDE\UserData\latest\user-data\logs\20200208T222148
SET VSCODE_NLS_CONFIG={"locale":"zh-cn","availableLanguages":{"*":"zh-cn"},"_languagePackId":"2ae16f5a9a23c98b985a67d503c3ac22.zh-cn","_translationsConfigFile":"D:\\programfiles\\updater.beta.20190604.4.win32\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn\\tcf.json","_cacheRoot":"D:\\programfiles\\updater.beta.20190604.4.win32\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn","_resolvedLanguagePackCoreLocation":"D:\\programfiles\\updater.beta.20190604.4.win32\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn\\e4de46724de34a5f46541818e9fee25971ac9969","_corruptedFile":"D:\\programfiles\\updater.beta.20190604.4.win32\\KendryteIDE\\UserData\\latest\\user-data\\clp\\2ae16f5a9a23c98b985a67d503c3ac22.zh-cn\\corrupted.info","_languagePackSupport":true}
SET VSCODE_NODE_CACHED_DATA_DIR=D:\programfiles\updater.beta.20190604.4.win32\KendryteIDE\UserData\latest\user-data\CachedData\e4de46724de34a5f46541818e9fee25971ac9969
SET VSCODE_PATH=D:\programfiles\updater.beta.20190604.4.win32\KendryteIDE\Application\app_1.34.1-beta_20190802.2
SET VSCODE_PID=55312
SET VSCODE_PORTABLE=D:\programfiles\updater.beta.20190604.4.win32\KendryteIDE\UserData\latest
SET WDIR=D:\PADS Projects;C:\MentorGraphics\9.5PADS\SDD_HOME\standard
SET WF_CLASSPATH=C:\MentorGraphics\9.5PADS\SDD_HOME\common\win32\lib
SET windir=C:\Windows
SET XILINX_FOR_ALTIUM_OVERRIDE= 
SET PYTHONHOME=D:/programfiles/updater.beta.20190604.4.win32/KendryteIDE/LocalPackage/python2library
SET PYTHONPATH=D:/programfiles/updater.beta.20190604.4.win32/KendryteIDE/LocalPackage/python2library;D:/programfiles/updater.beta.20190604.4.win32/KendryteIDE/LocalPackage/toolchain/share/gdb/python
SET PYTHONDONTWRITEBYTECODE=yes
SET CMAKE_MAKE_PROGRAM=make
SET KENDRYTE_IDE=yes
SET LANG=en_US.utf-8
"D:/programfiles/updater.beta.20190604.4.win32/KendryteIDE/LocalPackage/cmake/bin/cmake.exe" --build d:/k210-c/kendryte_3-standalone/build -- -j 7